# Generated by Django 5.2.5 on 2025-08-28 13:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
